#!/bin/bash

# A script for archiving the files, generated by "command.sh". The archives will be in  ~/linux_pt2/backup
# The archives that are older than 3 minutes will be moved to ~/linux_pt2/old_backup folder
# No arguments needed.

current_date=$(date +%Y-%m-%d)
files_dir=~/linux_pt2
backup_dir=$files_dir/backup
old_backup_dir=$files_dir/old_backup
log_dir=$files_dir/log

mkdir -p $backup_dir
mkdir -p $old_backup_dir
mkdir -p $log_dir

# Putting files from file folder to a backup folder

for file in "$files_dir"/*; 
    do
        echo "$file";
        name=$(basename "$file")g
        tar -czf "$files_dir/backup/${name}_${current_date}.tar.gz" "$file"
        rm $file

    done

# Putting archives from a backup folder to even older backups folder

for archive in "$backup_dir"/*;
    do
        if test "`find $archive -mmin +3`"; then 
            echo "${archive} is older than 3 minutes. Moving it to lod_backup"
            mv $archive "${old_backup_dir}/$(basename $archive)"
        fi
    done



